### ISSUE TITLE
MARKETPLACE - content & cta

### ISSUE THREAD

**Issue by sasha-astiadi** [threefoldfoundation/www_threefold_marketplace#10]
- [x] now.threefold.io : which is the commercial website about marketplace and has all solutions described

- [x] content from gridsome wiki ex now.threefold.io -> the new now.threefold.io which is based on new web framework

- [ ] on each commercial page there is "deploy now button"  
- [ ] when clicked, user go to auth page, see who user is, redirect to their evdc and their marketplace for that solution @xmonader 

- [ ] if you don't exist, ask to install TF Connect @xmonader

**Comment by Vilnite** [comment]
Aparently CTA should be through [invitation wizzard](https://github.com/threefoldfoundation/www_threefold_io/issues/16) and TF Connect.
Waiting on that.

**Comment by samtaggart** [comment]
This is blocked by the wizard readiness.

**Comment by sasha-astiadi** [comment]
the last part of the story is here https://github.com/threefoldtech/js-sdk/issues/2623

**Comment by sasha-astiadi** [comment]
@samtaggart is wizard readiness point 3?

**Comment by sasha-astiadi** [comment]
closing this https://github.com/threefoldtech/home/issues/1018
is  duplicated story on our project same as this one, so that only refer to this one instead.

our team is only doing the last part 2 parts of the story

- [ ] when clicked, user go to auth page, see who user is, redirect to their evdc and their marketplace for that solution
- [ ] if you don't exist, ask to install TF Connect
 is here threefoldtech/js-sdk#2623

**Comment by sasha-astiadi** [comment]
@Vilnite https://github.com/threefoldfoundation/www_threefold_io/issues/16 i dont think it has anything to do with this story

**Comment by Vilnite** [comment]
Foundation issues concern commercial side of the experience. All commercial websites will have wizzard as Call to Action, including Marketplace website - it won't go straight to deployment.

So we are waiting on wizzard to be ready to apply to this website.

**Comment by Vilnite** [comment]
Leaving it with invitation to join testing community for now

<img width="1155" alt="Screenshot 2021-03-03 at 11 35 38" src="https://user-images.githubusercontent.com/20182572/109785241-9c653280-7c14-11eb-9de9-9c826da110aa.png">

Will update to deployment links through cloud wiki as soon as we have sites set up with prefixes so we can link everything appropriately.
