### ISSUE TITLE
MARKETPLACE - update buttons

### ISSUE THREAD

**Issue by Vilnite** [threefoldfoundation/www_threefold_marketplace#2]
Please update all buttons to this:

<img width="347" alt="Screenshot 2021-02-12 at 18 48 04" src="https://user-images.githubusercontent.com/20182572/107796827-f33cc200-6d62-11eb-9e8d-e984cff6ee67.png">

**Comment by Vilnite** [comment]
@ehab-hassan you are working on master 
can you please switch to development? pull all your changes there.

**Comment by ehab-hassan** [comment]
yes I saw that :) fixing it now
