### ISSUE TITLE
MARKETPLACE - Misalignments between Marketplace apps on the website and the VDC

### ISSUE THREAD

**Issue by gmachtel** [threefoldfoundation/www_threefold_marketplace#20]
People will get confused by having other apps shown in the website and in the VDC Marketplace. 

Ex. 
- Blockchain Solutions: 
   - Presearch not there but already deployed
   - Matic, the next on the list, will become Polygon
- Discourse is in Decentralised We in VDC marketplace but in office on the website
- Commento is in Decentralised Office in VDC marketplace but in 'Community' on the website
- Decentralized Community vs. Decentralized WE
- Document Server and Onlyoffice have the same logo, but different naming (don't know which one is the correct one)
- Crystal Twin not appearing in VDC
- Bookstack called Knowledge Base in VDC
- Gridsome in Dec Community on website, in Dec Developer on VDC

**Comment by samtaggart** [comment]
- [x] Kristine create an image for Presearch
> - [x] Kristine add Presearch image to website (spot 1)
> - [x] Sam add content for Presearch page
- [x] Kristine change Matic to Polygon
> - [x] Kristine replace Matic with Polygon image
> - [x] Sam edit updated Polygon page
> - [x] Kristine: Change Matic to Polygon on marketplace
> - [x] Kristine make Presearch 1, Polygon 2, DigiByte 3, & Dash 4 (in order)
- [x] Kristine change Decentralized Community to Decentralized We on website
- [x] Kristine move Discourse to Decentralized We on website
- [x] Kristine change text for commento on website
> - [x] Kristine replace Commento image on website with new image
> - [x] Kristine: Move Commento to Decentralized We on marketplace
> - [x] Kristine: Marketplace: "Commento lets you embed comments without giving up your privacy."
- [x] Kristine change OnlyOffice image to Document Server
> - [x] Kristine replace OnlyOffice image with Document Server
- [x] Kristine remove Crystal Twin from website
- [x] Kristine change BookStack image to Knowledge Base
> - [x] Kristine replace Bookstack image with Knowledge Base
- [x] Kristine move Gridsome to Decentralized Developer on website
- [x] Sam look for other inconsistencies

**Comment by samtaggart** [comment]
Will finish this and get the rest assigned today to be finished on Sunday. The images Zia sent me initially need tweaks.

**Comment by samtaggart** [comment]
Kristine crushed her part. I will finish on Sunday with Benje's help.

**Comment by samtaggart** [comment]
I need Benje's help so will finish this tomorrow

**Comment by BenjellounO** [comment]
@samtaggart  here's the Updated Polygon (Matic) wiki:  https://secure.threefold.me/pad/#/2/pad/edit/ei8mZcJ8xkvY1KGRd0FdXXs2/

**Comment by samtaggart** [comment]
I went through and did a lot of fixes but found a couple issues which need to be fixed:

- [ ] Look at Publishtools
- [ ] Look at PeerTube
- [ ] Look at Servlerless
- [ ] Do another run-through / comparison tomorrow with fresh eyes

**Comment by samtaggart** [comment]
Creating a new issue, this one is getting too messy.
