### ISSUE TITLE
MARKETPLACE: Add missing apps

### ISSUE THREAD

**Issue by samtaggart** [threefoldfoundation/www_threefold_marketplace#23]
MONITORING STACK
- [ ] @samtaggart Create page information
- [ ] @Vilnite Implement page information
- [ ] @samtaggart Find one-liner for "app card"
- [ ] @Vilnite Create "app card" and add to apps page in Decentralized Developer & All, alphabetically

KUBEAPPS
- [ ] @samtaggart Create page information
- [ ] @Vilnite Implement page information
- [ ] @samtaggart Find one-liner for "app card"
- [ ] @Vilnite Create "app card" and add to apps page in Decentralized Developer & All, alphabetically

ETCD
- [ ] @samtaggart Create page information
- [ ] @Vilnite Implement page information
- [ ] @samtaggart Find one-liner for "app card"
- [ ] @Vilnite Create "app card" and add to apps page in Decentralized Developer & All, alphabetically

OWNCLOUD
- [ ] @samtaggart Create page information
- [ ] @Vilnite Implement page information
- [ ] @samtaggart Find one-liner for "app card"
- [ ] @Vilnite Create "app card" and add to apps page in Decentralized Developer & All, alphabetically

MASTODON
- [ ] @samtaggart Create page information
- [ ] @Vilnite Implement page information
- [ ] @samtaggart Find one-liner for "app card"
- [ ] @Vilnite Create "app card" and add to apps page in Decentralized Developer & All, alphabetically

POLYGON
- [ ] Update

OTHERS?
- [ ] Check with Sasha

**Comment by Vilnite** [comment]
See in circles tool: https://circles.threefold.me/project/despiegk-product_web_threefold/issue/36
