### ISSUE TITLE
MARKETPLACE: Blend Home Page & About Page

### ISSUE THREAD

**Issue by samtaggart** [threefoldfoundation/www_threefold_marketplace#24]
This addresses Kristof feedback of "https://marketplace.threefold.io/about needs to be the home page, much more powerful" in Issue https://github.com/threefoldfoundation/home/issues/123.

We don't feel that we can simply swap the pages so we will blend them.

New order should be:

- [x] Better Safe Never Sorry (Home) >>> Change button link to wiki (https://new.threefold.io/info/cloud#/cloud__evdc_marketplace)
- [x] Marketplace Favorites (Home)
- [x] Power of P2P (About)
- [x] Values (About)
- [x] Give the Gift (About)
- [x] Made Possible (About)
- [x] Can't Find the Perfect App? (Home)

And remove:
- [x] The most Complete (Home)

**Comment by Vilnite** [comment]
Moved Made Possible by the ThreeFold Grid one section above for so that 2 headers wouldn't follow each other.
