### ISSUE TITLE
MARKETPLACE: Changes (before Sunday's push possible?)

### ISSUE THREAD

**Issue by samtaggart** [threefoldfoundation/www_threefold_marketplace#29]
- [x] On home, The Power of P2P component should look like it did on the other page, not use a card (it's being cut off) – if there is an issue, let me know and we can find a solution : 

@samaradel can you please apply same approach we have on cloud website for cards component?  (make space for much larger image)

- [x] On Apps page, please add a color background to the "We are currently in BETA version" component (I'm unsure which color to use but should be something from the website or a light grey)
- [x] On home, add "We are currently in BETA version" component (copy-paste the text) to home right above the grid image at the bottom of the page beneath Give the Gift of Empowerment
- [x] On home, Remove Can't find the perfect app? (keep the grid image beneath it) and move Made Possible component to the bottom, above the grid image and below the CTA

**Comment by ehab-hassan** [comment]
sorry don't understand issue ,can u send screenshot what is cutting? Samar is Off today

**Comment by samtaggart** [comment]
Will take a look ASAP. I am trying to get my publishtools to work.

But you can see how it appears now live on marketplace.threefold.io/about

**Comment by samtaggart** [comment]
Ah OK it looks like someone fixed it up a bit. It's looking good, would just want to make that graphic bigger

<img width="974" alt="Screen Shot 2021-03-21 at 11 37 47 AM" src="https://user-images.githubusercontent.com/50134479/111898904-fbf77680-8a39-11eb-87b3-ef27a6efa4e2.png">
