### ISSUE TITLE
MARKETPLACE: Create Casper Labs for Apps

### ISSUE THREAD

**Issue by samtaggart** [threefoldfoundation/www_threefold_marketplace#33]
- [x] @BenjellounO create Casper Labs page info, follow format for other blockchain apps
- [x] @samtaggart review page info, convert to markdown for Kristine

**Comment by BenjellounO** [comment]
Caper Labs page info is In Progress

**Comment by samtaggart** [comment]
The announcement was moved to next week, the draft is done, we will post this by next Thursday
