### ISSUE TITLE
MARKETPLACE: Review of landing

### ISSUE THREAD

**Issue by Sacha96** [threefoldfoundation/www_threefold_marketplace#35]
- [x] remove current header block >> replace with power of P2P as header. 

<img width="1122" alt="Screenshot 2021-04-04 at 15 46 32" src="https://user-images.githubusercontent.com/54844940/113509203-8f5d9b00-9554-11eb-9a78-31b5619a799a.png">

so use this as header. move picture to right and text to left. and add button know more (like current) and lead to same link 
- [x] then follow with this block: 
<img width="1283" alt="Screenshot 2021-04-04 at 15 48 31" src="https://user-images.githubusercontent.com/54844940/113509244-d5b2fa00-9554-11eb-99b6-75d9d22e860f.png">

- [x] from that point rest of page stays the same..
<img width="1240" alt="Screenshot 2021-04-04 at 15 49 00" src="https://user-images.githubusercontent.com/54844940/113509261-e82d3380-9554-11eb-9677-b39ede24154a.png">

**Comment by Sacha96** [comment]
<img width="1178" alt="Screenshot 2021-04-06 at 20 52 56" src="https://user-images.githubusercontent.com/54844940/113756622-e5c40880-9711-11eb-8405-5fdad5c857c9.png">

Add button >> choose your app  (link to app page)
Add button >> deploy your environment (link to https://new.threefold.io/info/cloud#/cloud__evdc_marketplace)

**Comment by Vilnite** [comment]
@ehab-hassan can you please 
- [x] add those two buttons below GIVE THE GIFT OF EMPOWERMENT component
- [x] Also check if you can add more space between all components on home page (they all are quite squeezed together)

thank you :)
