### ISSUE TITLE
Testnet already enables Blockchain Node Deployment

### ISSUE THREAD

**Issue by maximilianrang** [threefoldfoundation/www_threefold_marketplace#37]
In order to benefit from Node deployments on a partnership and PR level, we can´t have them available right now already.

Please move all of them to "coming soon", so we can unlock them once we have proper PR and partnership agreements in place.

**Comment by xmonader** [comment]
please open in the right repo.

**Comment by gmachtel** [comment]
It’s about testnet nodes. These are available without any guarantee about continuity of service etc. And as long as we’re on testnet, we cannot promise anything more. So what’s the issue ? This is a simple showing the capabilities of the grid, not meant to do PR or partnership announcements.

**Comment by BenjellounO** [comment]
no need to change them to "coming soon".

Reason N1: we're still testing them internally
Reason N2: even if they're available on the marketplace/VDC, they are not public yet, the only folks aware of that is the Blockchain teams @abdulgig  and I are working with to validate the testing and the deployment process. 
Reason N3: turning them back into "coming soon" will affect our credibility with our Blockchain partners. 

so no need to. if any questions, remarks or suggestions around the BC solutions, please shoot them my way, and Abdul's. Thanks

**Comment by abdulgig** [comment]
@gmachtel, Exactly !  Infact that is what testnet is for, to burn "testing cycles" and avoid them on production network

Ideally more and more of these solutions should be on testnet so that communities can test them inside out. So by the time we are ready for Mainnet, these solutions would have already been matured and gained acceptance.
