### ISSUE TITLE
Fix Node  Deployment Capacity Allocation Problem

### ISSUE THREAD

**Issue by maximilianrang** [threefoldfoundation/www_threefold_marketplace#38]
When deploying a Digibyte node, the process fails unless you select at least Platinum. We should disable the lower packages so the process runs smoothly for everyone.

**Comment by xmonader** [comment]
why are issues getting opened here? please open issues in the right repo. threefoldtech/js-sdk

**Comment by xmonader** [comment]
People can add larger nodes on any of the packages
