### ISSUE TITLE
Cookie policy banner is not showing

### ISSUE THREAD

**Issue by Vilnite** [threefoldfoundation/www_threefold_marketplace#39]
Noticed that on all other websites we have cookie policy banner:

<img width="1440" alt="Screenshot 2021-07-14 at 20 09 44" src="https://user-images.githubusercontent.com/20182572/125664585-d76e1db3-8d4e-4de4-93bb-79f9520834ee.png">

except on Marketplace.

Please add.

**Comment by samaradel** [comment]
![image](https://user-images.githubusercontent.com/11662805/125756653-8a6ed4c0-f2e0-42c1-b89b-a3d908729218.png)
check it in private window
